### ISSUE TITLE
Syslog support

### ISSUE THREAD

**Issue by zloidemon** [tris-foundation/log#1]
Write logs into syslog

**Comment by tonyfreeman** [comment]
Please provide more information.
The current Log implementations allows you to specify your own delegate.
```swift
Log.delegate = { level, message in
    syslog("level: \(level) message: \(message)")
}
```

**Comment by zloidemon** [comment]
Yes it is solution to write own bindings to pass logs data into delegate. But `syslog` doesn't include into your library.

**Comment by tonyfreeman** [comment]
You mean you want syslog delegate implemented in the package? 
This would require "Network" dependency which in turn depends on Stream, Async and Platform.
Initially is was intended to provide a thin layer so you can inject anything you want. It's a bit weird for Log to depend on Network i think, especially if you only write in stderr.
But i'm thinking of merging Network with File (not public yet) to the one IO package, 
so it would make more sense in most cases. (For example Network requires File to read resolv.conf)
for now you can write your own Syslog, something like this:

```swift
import Log
import Network

var retry = false
var syslog: Socket? = nil

#if os(macOS)
    var log = try! Socket.Address(unix: "/dev/log")
#else
    var log = try! Socket.Address(unix: "/var/run/syslog")
#endif

struct Syslog {
    public static func delegate(level: Level, message: String) -> Void {
        if syslog == nil {
            guard let socket =
                try? Socket(family: .local, type: .datagram) else {
                    return
            }

            syslog = socket
        }
        let bytes = [UInt8](message.utf8)
        do {
            _ = try syslog!.send(bytes: bytes, to: log)
        } catch {
            if !retry {
                // try again
                syslog = nil
                retry = true
                delegate(level: level, message: message)
            }
        }
        retry = false
    }
}
```

and use it in your code:
```swift
Log.delegate = Syslog.delegate
```
